---
squash: false
build_from:
  arm64: sabourinj/barcodebuddy:latest
  aarch64: sabourinj/barcodebuddy:latest
  amd64: sabourinj/barcodebuddy:latest
  armv7: sabourinj/barcodebuddy:latest
  i386: sabourinj/barcodebuddy:latest
args: {}
